#!/usr/bin/env bash
#
# Inherits or removes a folder from the common folder into a system-specific folder.

set -e

add=false
remove=false

case $1 in
  add)
    echo "Linking $2 into $3"
    add=true
    ;;
  remove)
    echo "Removing $2 from $3"
    remove=true
    ;;
  *)
    echo "Usage: $0 {add|remove} git macos"
    exit 1
    ;;
esac

# Navigate to the destination parent folder as with relative symlinks both the src and target  need to be relative to the target folder.
cd "$(dirname "$0")/../$3"

src="../common/$2"
dst="common-$2"

if [ ! -d "$src" ] ; then
  echo "$src is not a directory or does not exist. Exiting."
  exit 1
fi

if [ -f "$dst" ] ; then
  echo "$dst exists as a file (not a symlink). Skipping."
fi

if [ -d "dst" ] ; then
  echo "$dst exists as a directory (not a symlink). Skipping."
fi

if [ "$add" = true ] ; then
  if [ -L "$dst" ] ; then
    echo "$dst already exists as a symlink. Skipping."
  else
    ln -s "$src" "$dst"
  fi
fi

if [ "$remove" = true ] ; then
  if [ -L "$dst" ] ; then
    rm "$dst"
  else
    echo "$dst does not exist. Skipping."
  fi
fi

